name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create cypress.env.json
        run: |
          echo '{
            "users": {
              "standard": {
                "username": "standard_user",
                "password": "secret_sauce"
              },
              "locked": {
                "username": "locked_out_user",
                "password": "secret_sauce"
              }
            }
          }' > cypress.env.json
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true 