name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create cypress.env.json
        run: |
          echo '{
            "standard_username": "standard_user",
            "locked_out_username": "locked_out_user",
            "password": "secret_sauce"
          }' > cypress.env.json

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mochawesome-report
          path: cypress/reports 