name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      # Create cypress.env.json file using GitHub secrets
      - name: Create Cypress environment file
        run: |
          echo '{
            "users": {
              "standard": {
                "username": "standard_user",
                "password": "secret_sauce"
              },
              "locked": {
                "username": "locked_out_user",
                "password": "secret_sauce"
              }
            }
          }' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: false

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-report
          path: cypress/reports 